

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      FLASK_APP: "app"
      FLASK_ENV: "development"



  frontend:
    build:
      context: ./frontend      
      dockerfile: Dockerfile   
    container_name: domain-inspector-frontend
    #depends_on:
    #  - api
    ports:
      - "80:80"             
    restart: unless-stopped